<?php

/**
 * PluginPaygroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPaygroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPaygroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPaygroup');
    }
}